"""deleted moderatoes

Revision ID: 479ad1a35a1f
Revises: c3e1c6e985a7
Create Date: 2022-09-22 17:02:05.801029

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479ad1a35a1f'
down_revision = 'c3e1c6e985a7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'is_moderator')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('is_moderator', sa.BOOLEAN(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
