"""added cancelled status

Revision ID: 61dab1a0e234
Revises: c9aa4f99397b
Create Date: 2022-09-26 16:21:05.106915

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61dab1a0e234'
down_revision = 'c9aa4f99397b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('draw', sa.Column('cancelled', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('draw', 'cancelled')
    # ### end Alembic commands ###
