"""added balance

Revision ID: 67ac151dba7a
Revises: 61dab1a0e234
Create Date: 2022-09-28 15:35:58.175609

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67ac151dba7a'
down_revision = '61dab1a0e234'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('user', sa.Integer(), nullable=True),
    sa.Column('balance', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user'], ['subscriber.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    op.add_column('subscriber', sa.Column('balance', sa.Integer(), nullable=False))
    op.add_column('subscriber', sa.Column('subscribed_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('subscriber', 'subscribed_date')
    op.drop_column('subscriber', 'balance')
    op.drop_table('user_profile')
    # ### end Alembic commands ###
