"""added user number and status

Revision ID: c3e1c6e985a7
Revises: eca710772ee4
Create Date: 2022-09-22 15:23:37.477041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3e1c6e985a7'
down_revision = 'eca710772ee4'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('subscriber', sa.Column('phone_number', sa.BigInteger(), nullable=False))
    op.create_unique_constraint(None, 'subscriber', ['phone_number'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'subscriber', type_='unique')
    op.drop_column('subscriber', 'phone_number')
    # ### end Alembic commands ###
