"""added draw model

Revision ID: c9aa4f99397b
Revises: 479ad1a35a1f
Create Date: 2022-09-24 16:09:51.005203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c9aa4f99397b'
down_revision = '479ad1a35a1f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draw',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('preview_photo_path', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('start_date', sa.DateTime(), nullable=True),
    sa.Column('end_date', sa.DateTime(), nullable=True),
    sa.Column('winners_count', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('Id')
    )
    op.create_table('draw_member',
    sa.Column('Id', sa.Integer(), nullable=False),
    sa.Column('member', sa.Integer(), nullable=True),
    sa.Column('draw', sa.Integer(), nullable=True),
    sa.Column('winner', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['draw'], ['draw.Id'], ),
    sa.ForeignKeyConstraint(['member'], ['subscriber.Id'], ),
    sa.PrimaryKeyConstraint('Id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draw_member')
    op.drop_table('draw')
    # ### end Alembic commands ###
