"""deleted trash model

Revision ID: e996159ce98d
Revises: 67ac151dba7a
Create Date: 2022-09-28 16:11:50.916294

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e996159ce98d'
down_revision = '67ac151dba7a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_profile')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_profile',
    sa.Column('Id', sa.INTEGER(), server_default=sa.text('nextval(\'"user_profile_Id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('user', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('balance', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user'], ['subscriber.Id'], name='user_profile_user_fkey'),
    sa.PrimaryKeyConstraint('Id', name='user_profile_pkey')
    )
    # ### end Alembic commands ###
